title: Documentation Security
description: Documentation blog
author: Vnclouds
logo: https://i.imgur.com/JA1DbUr.png
github: #
about: security base

baseurl: "https://beta.vnclouds.co/Documentation"
url: "https://beta.vnclouds.co/Documentation"

allowsearch: true

disqus_shortname: vnclouds
google_analytics: UA-72862926-1

share:
  twitter_username: @UuVhb
  fb_appid: 303980933541053


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
  gems:
    - jekyll-seo-tag
